name: Continuous Delivery

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-26.04
    steps:
      - name: login the server
        run: |
                echo ${{ secrets.SSH_PRIVATE_KEY }} | sshpass ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_IP }} "cat file.txt"
